services:
  nuclei-scanner:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./scan-results:/app/results

  sast-scanner:
    build:
      context: .
      dockerfile: "SemgrepRules/Dockerfile"
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
